#!/usr/bin/env bash

usage(){
  cat <<EOS
Usage:

CMD: ${0##*/} test.tsv

EOS

exit 0
}

TSV_FILE_NAME=$1;shift

[ -z ${TSV_FILE_NAME} ] && usage

INPUT_FILE_EXTENSION=$(echo $TSV_FILE_NAME | ruby -F'\.' -anle 'puts $F[$F.size-1]')

if [ ! $INPUT_FILE_EXTENSION == "tsv" ];then

  usage

fi

JSON_FILE_NAME=${TSV_FILE_NAME//.*}.json

[ -z ${JSON_FILE_NAME} ] && usage

cat $TSV_FILE_NAME | \
	jq -R './"\n"|map(./"\t")|flatten' | \
	jq -s '. as $all_entry|.[0] as $head_entry|.[1:($all_entry|length)] as $detail_entry|$detail_entry|length as $detail_cnt|[range(0;$detail_cnt)]|map(. as $row|[range(0;$detail_entry[$row]|length)]|map(. as $col|{($head_entry[$col]):$detail_entry[$row][$col]}))[]|reduce .[] as $entry({};.+$entry)' | \
	jq -s '' >$JSON_FILE_NAME
