#!/usr/bin/env bash

INCLUDE_LIST="executable|Ruby script"
EXCLUDE_LIST="\.git|P00-|T01-|sh$"

SCRIPT_CMD_DIR_NAME=script-cmd

usage(){
cat <<EOS
Usage:
   PRE: git clone https://github.com/ukijumotahaneniarukenia/$SCRIPT_CMD_DIR_NAME.git
   CMD: bash $0 | bash
EOS

exit 0

}

if [ ! -d $HOME/$SCRIPT_CMD_DIR_NAME ];then

  usage

fi

find $HOME/$SCRIPT_CMD_DIR_NAME -type f | grep -vP "$EXCLUDE_LIST" | xargs file | grep -P "$INCLUDE_LIST" | cut -d':' -f1 | sort -r | \
  while read f;do
    CMD_HOST_VERSION=$(echo $f|grep -Po '[0-9]+?(-[0-9]+)+');
    echo ln -fsr $f $HOME/.local/$SCRIPT_CMD_DIR_NAME/bin/${f##*/};
    echo ln -fsr $f $HOME/.local/$SCRIPT_CMD_DIR_NAME/bin/${f##*/}-$CMD_HOST_VERSION;
  done
