#!/usr/bin/env bash

usage(){
cat <<EOS
Usage:
   IN: echo unkoMoriMori | ${0##*/}
  OUT: UnkoMoriMori
EOS

exit 0

}

main(){
  ARGS=($(cat -));

  if [[ 0 -eq ${#ARGS[@]} ]] ;then

    usage

  fi

  for(( i=0;i<${#ARGS[@]};i++ ));do

    echo ${ARGS[$i]} | ruby -F'(?=[A-Z])' -anle 'print $F[0].capitalize,$F[1..$F.size-1].join("")'

  done

}

[ -p /dev/stdin ] && cat - | main
[ -p /dev/stdin ] || usage
