#!/usr/bin/env bash

usage(){
cat <<EOS
Usage:
   IN: echo unko_mori_mori | ${0##*/}
  OUT: UNKO_MORI_MORI
EOS

exit 0

}

main(){
  ARGS=($(cat -));

  STR=${ARGS[0]}

  if [ -z "${STR}" ] ;then

    usage

  fi

  echo "${STR}" | ruby -F_ -anle 'print $F.map(&:upcase).join("_")'

}

[ -p /dev/stdin ] && cat - | main
[ -p /dev/stdin ] || usage
