#!/usr/bin/env bash

usage(){
cat <<EOS
Usage:
   IN: echo unkoMoriMori | ${0##*/}
  OUT: UNKO_MORI_MORI
EOS

exit 0

}

main(){
  ARGS=($(cat -));

  if [[ 0 -eq ${#ARGS[@]} ]] ;then

    usage

  fi

  for(( i=0;i<${#ARGS[@]};i++ ));do

    echo ${ARGS[$i]} | ruby -F'(?=[A-Z])' -anle 'puts $F.map(&:upcase).join("_")'

  done

}

[ -p /dev/stdin ] && cat - | main
[ -p /dev/stdin ] || usage
