#!/usr/bin/env bash

usage(){

cat <<EOS

Usage:

  CMD: ${0##*/} test.xml

EOS

exit 0

}

INPUT_FILE_NAME=$1;shift;

if [ -z $INPUT_FILE_NAME ];then

  usage

fi

echo  $INPUT_FILE_NAME | java -jar /home/aine/script-sketch/java/00010-java-XMLファイルをJSONファイルへ変換/nnn/target/xml2json-1.0-SNAPSHOT-jar-with-dependencies.jar
