#!/usr/bin/env bash

usage(){
cat <<EOS

USAGE:

  IN: ${0##*/} @a @{a..d}

  OUT: @a @b @c @d

  CMD_LIST:

  $(cd $LOCATION_PACKAGE_JSON && npm run)

EOS

exit 0

}

LOCATION_PACKAGE_JSON=$HOME/script-cmd/npm/6-14-9/nak5

TARGET_CMD_LIST=("${@}")
REMAIN_ARGS=

#echo ${TARGET_CMD_LIST[@]}  #配列全要素
#echo ${TARGET_CMD_LIST[0]}  #配列先頭要素
#echo ${!TARGET_CMD_LIST[@]} #配列インデックス
#echo ${#TARGET_CMD_LIST[@]} #配列要素数

if [[ ${#TARGET_CMD_LIST[@]} -eq 0 ]];then

  usage

fi

if [ ${TARGET_CMD_LIST[0]} == "nak5" ];then

  REMAIN_ARGS=${TARGET_CMD_LIST[@]:1}

  cd $LOCATION_PACKAGE_JSON && npm run nak5 $REMAIN_ARGS

  exit 0

fi

cd $LOCATION_PACKAGE_JSON && npm run "${@}" 1>/dev/null 2>&1

if [[ $? -eq 1 ]];then

  usage

fi

cd $LOCATION_PACKAGE_JSON && npm run "${@}" | sed -n '1,4!p'
