#!/usr/bin/env bash

usage(){
cat <<EOS
Usage:
  CATEGORY_NAME_LIST:

  C C Cc Cf Cn Co Cs
  L L LC Ll Lm Lo Lt Lu
  M M Mc Me Mn
  N N Nd Nl No
  P P Pc Pd Pe Pf Pi Po Ps
  S S Sc Sk Sm So
  Z Z Zl Zp Zs


   IN: ${0##*/} Lu
  OUT:

EOS

exit 0

}

CATEGORY_NAME="$1";shift;

if [ -z "$CATEGORY_NAME" ];then

  usage

fi

perl -C -MUnicode::UCD -E '$,="\t";($i,$r)=Unicode::UCD::prop_invmap("General Category");@a=@{$i};map{say @{$i}[$_],@{$r}[$_]}(0..$#a)'|awk -F'\t' '{a[NR]=$1","$2}END{for(e in a){split(a[e+1],b,",");split(a[e],c,",");print e,c[2],c[1],b[1]-1==-1?1114112:b[1]-1,((b[1]-1==-1?1114112:b[1]-1)-c[1]+1)}}' OFS='\t'|awk -F'\t' '{print $2,$3,$4}'|sort -k1,1 -k 2n|\
  grep "$CATEGORY_NAME"|\
  perl -C -MString::Random -anlE '($k,$s,$e)=@F;$l=$l+($e-$s+1);$t=sprintf(qq/\\x{%X}-\\x{%X}/,$s,$e);push(@b,$t);END{say eval"String::Random->new->randregex("."\"[".(join "",@b)."]{".$l."}"."\")"}' 2>/dev/null
