#!/usr/bin/env bash

INCLUDE_LIST="executable|Ruby script"
EXCLUDE_LIST="\.git|([P|T|L|M][0-9])"

SCRIPT_SEARCH_DIR_NAME=script-search
SCRIPT_CMD_DIR_NAME=script-cmd

usage(){
cat <<EOS
Usage:
   PRE: git clone https://github.com/ukijumotahaneniarukenia/$SCRIPT_SEARCH_DIR_NAME.git
        git clone https://github.com/ukijumotahaneniarukenia/$SCRIPT_CMD_DIR_NAME.git
   CMD: bash $0 | bash
EOS

exit 0

}

if [ ! -d $HOME/$SCRIPT_SEARCH_DIR_NAME ];then

  usage

fi

if [ ! -d $HOME/$SCRIPT_CMD_DIR_NAME ];then

  usage

fi

find $HOME/$SCRIPT_SEARCH_DIR_NAME $HOME/$SCRIPT_CMD_DIR_NAME -type f | grep -vP "$EXCLUDE_LIST" | xargs file | grep -P "$INCLUDE_LIST" | cut -d':' -f1 | sort -r | \
  while read f;
    do echo ${f##*/};
  done
