#!/usr/bin/env bash

usage(){
cat <<EOS
Usage:
   PRE: git clone https://github.com/ukijumotahaneniarukenia/script-search.git
   CMD: bash $0
EOS

exit 0

}

INCLUDE_LIST="executable|Ruby script"
EXCLUDE_LIST="\.git|P00-|T01-|sh$"

SCRIPT_SEARCH_DIR_NAME=script-search
SCRIPT_CMD_DIR_NAME=script-cmd

if [ ! -d $SCRIPT_SEARCH_DIR_NAME ];then

  usage

fi

find $HOME/$SCRIPT_SEARCH_DIR_NAME $HOME/$SCRIPT_CMD_DIR_NAME -type f | grep -vP "$EXCLUDE_LIST" | xargs file | grep -P "$INCLUDE_LIST" | cut -d':' -f1 | sort -r | \
  while read f;
    do echo ${f##*/};
  done
