#!/usr/bin/env bash

usage(){
cat <<EOS
Usage:
   IN: $0 ジーナ マルコ 紅の豚
  OUT: %E3%82%B8%E3%83%BC%E3%83%8A+%E3%83%9E%E3%83%AB%E3%82%B3+%E7%B4%85%E3%81%AE%E8%B1%9A
EOS

exit 0

}

LIST="$@";shift;

if [ -z "$LIST" ];then

  usage

fi

echo "$LIST" | ruby -rcgi -anle 'a={};a[$_]=CGI.escape($_);puts a[$_]'
