#!/usr/bin/env bash

usage(){
cat <<EOS
Usage:
   IN: echo Unko-Mori-Mori | ${0##*/}
  OUT: UnkoMoriMori
EOS

exit 0

}

main(){
  ARGS=($(cat -));

  if [[ 0 -eq ${#ARGS[@]} ]] ;then

    usage

  fi

  for(( i=0;i<${#ARGS[@]};i++ ));do

    echo ${ARGS[$i]} | ruby -F- -anle 'print $F.join("")'

  done

}

[ -p /dev/stdin ] && cat - | main
[ -p /dev/stdin ] || usage
