#!/usr/bin/env bash

usage(){
cat <<EOS
Usage:
   IN: echo UNKO_MORI_MORI | ${0##*/}
  OUT: UnkoMoriMori
EOS

exit 0

}

main(){
  ARGS=($(cat -));

  STR=${ARGS[0]}

  if [ -z "${STR}" ] ;then

    usage

  fi

  echo "${STR}" | ruby -F_ -anle 'print $F.map{|e|e.slice(0)+e.slice(1..e.size).downcase}.join("")'

}

[ -p /dev/stdin ] && cat - | main
[ -p /dev/stdin ] || usage
