#!/usr/bin/env bash

usage(){
cat <<EOS
Usage:
   IN: echo UNKO_MORI_MORI | ${0##*/}
  OUT: unko_mori_mori
EOS

exit 0

}

main(){
  ARGS=($(cat -));

  STR=${ARGS[0]}

  if [ -z "${STR}" ] ;then

    usage

  fi

  echo "${STR}" | ruby -F_ -anle 'print $F.map(&:downcase).join("_")'

}

[ -p /dev/stdin ] && cat - | main
[ -p /dev/stdin ] || usage
