#!/usr/bin/env bash

usage(){
cat <<EOS
Usage:
   IN: echo UNKO_MORI_MORI | ${0##*/}
  OUT: unko_mori_mori
EOS

exit 0

}

main(){
  ARGS=($(cat -));

  if [[ 0 -eq ${#ARGS[@]} ]] ;then

    usage

  fi

  for(( i=0;i<${#ARGS[@]};i++ ));do

    echo ${ARGS[$i]} | ruby -F_ -anle 'print $F.map(&:downcase).join("_")'

  done

}

[ -p /dev/stdin ] && cat - | main
[ -p /dev/stdin ] || usage
