#!/usr/bin/env bash

usage(){
cat <<EOS
Usage:
   IN: echo unko-mori-mori | ${0##*/}
  OUT: unkoMoriMori
EOS

exit 0

}

main(){
  ARGS=($(cat -));

  STR=${ARGS[0]}

  if [ -z "${STR}" ] ;then

    usage

  fi

  echo "${STR}" | ruby -F- -anle 'print $F[0],$F[1..$F.size-1].map(CMD_STR:capitalize).join("")'

}

[ -p /dev/stdin ] && cat - | main
[ -p /dev/stdin ] || usage
