#!/usr/bin/env bash

usage(){
cat <<EOS

USAGE:

  ACTION : Please Execute shell-gei-get-prepare-bash Before Execute shell-gei-get-execute-bash
  
  CMD : ${0##*/} 1>$HOME/${0##*/}.log 2>&1 &

EOS

exit 0

}

SHELL_GEI_HASH_TAG='#shellgei|#shellgei2|#ゆるシェル|#シェル芸|#危険シェル芸|#ゆるシェル|#除夜のシェル芸|#新春シェル芸|#年越しシェル芸|#Shellgei'

INPUT_FILE_NAME="a.txt";shift;

if [ ! -f "$INPUT_FILE_NAME" ];then

  usage

fi

if [ ! -s "$INPUT_FILE_NAME" ];then

  chrome 'http://localhost:9090' --headless

fi


cat $INPUT_FILE_NAME | sed -r '/^$/d;' | sed -r 's/^ +//g' | awk -v SHELL_GEI_HASH_TAG=$SHELL_GEI_HASH_TAG '{if($0 ~ SHELL_GEI_HASH_TAG) {print 1,$0}else{print 0,$0}}' |awk 'BEGIN{a=0}{a=a+$1;$1="";print a"========="$0}' |ruby -F'=========' -anle 'BEGIN{a=[]};a<<$F;END{a.group_by{|k,v|k}.map{|kk,vv|puts vv.map{|i|i[1]}.join(" ")+"\n"*10}}'

