#!/usr/bin/env bash

usage(){
cat <<EOS
Usage:
   IN: echo unko-mori-mori | ${0##*/}
  OUT: Unko-Mori-Mori
EOS

exit 0

}

main(){
  ARGS=($(cat -));

  STR=${ARGS[0]}

  if [ -z "${STR}" ] ;then

    usage

  fi

  echo "${STR}" | ruby -F- -anle 'print $F.map{|e|e.slice(0).upcase+e.slice(1..e.size-1).downcase}.join("-")'

}

[ -p /dev/stdin ] && cat - | main
[ -p /dev/stdin ] || usage
