#!/usr/bin/env bash

usage(){
cat <<EOS
Usage:
   IN: echo unko-mori-mori | ${0##*/}
  OUT: Unko-Mori-Mori
EOS

exit 0

}

main(){
  ARGS=($(cat -));

  if [[ 0 -eq ${#ARGS[@]} ]] ;then

    usage

  fi

  for(( i=0;i<${#ARGS[@]};i++ ));do

    echo ${ARGS[$i]} | ruby -F- -anle 'print $F.map{|e|e.slice(0).upcase+e.slice(1..e.size-1).downcase}.join("-")'

  done

}

[ -p /dev/stdin ] && cat - | main
[ -p /dev/stdin ] || usage
