#!/usr/bin/env bash

INCLUDE_LIST="executable|Ruby script|shared object"
EXCLUDE_LIST="\.git|[A-Z][0-9]{2}"

SCRIPT_SEARCH_DIR_NAME=script-search
INSTALL_DIR_NAME=$HOME/.local/$SCRIPT_SEARCH_DIR_NAME/bin

usage(){
cat <<EOS
Usage:
   PRE: cd $HOME && rm -rf $SCRIPT_SEARCH_DIR_NAME && git clone https://github.com/ukijumotahaneniarukenia/$SCRIPT_SEARCH_DIR_NAME.git && mkdir -p $INSTALL_DIR_NAME
   CMD: ${0##*/}
EOS

exit 0

}

if [ ! -d $HOME/$SCRIPT_SEARCH_DIR_NAME ];then

  usage

fi

if [ ! -d $INSTALL_DIR_NAME ];then

  usage

fi

mkdir -p $INSTALL_DIR_NAME

find $HOME/$SCRIPT_SEARCH_DIR_NAME -type f | grep -vP "$EXCLUDE_LIST" | xargs file | grep -P "$INCLUDE_LIST" | cut -d':' -f1 | sort -r | \
  while read f;do
    echo ln -fsr $f $HOME/.local/$SCRIPT_SEARCH_DIR_NAME/bin/${f##*/} | bash
  done
