#!/usr/bin/env python3
import re
import sys
import os
import math
from PIL import Image

TARGET_WIDTH_LIST = [180, 240,320,480,640,800,1200]

def usage():
    script_file_name = re.sub(".*/", "", __file__)
    usage = """
USAGE:

CMD:  {filename} test.png
""".format(filename=script_file_name)

    print(usage)
    sys.exit(0)

def execute(target_file_path):
  target_file = target_file_path.split(".")
  target_file_name = target_file[0]
  target_file_extension = "." + target_file[1]
  img = Image.open(target_file_name + target_file_extension)
  img_size = img.size
  img_width = img_size[0]
  img_height = img_size[1]

  for target_width in TARGET_WIDTH_LIST:
    img_ratio = img_height/img_width

    img_resize_lanczos = img.resize((target_width,math.floor(img_ratio * target_width)), Image.LANCZOS)

    img_resize_lanczos.save(target_file_name + '-' + str(target_width) + 'h' + '-' + str(math.floor(img_ratio * target_width)) + 'w' + target_file_extension)

def main():

    try:

      if (len(sys.argv[1:])) == 0:

          usage()

      else:

        input_file_path_list = sys.argv[1:]

        for target_input_file_path in input_file_path_list:

          if not os.path.exists(target_input_file_path):
            pass

          execute(target_input_file_path)

    except KeyboardInterrupt:

        usage()

if __name__ == "__main__":
    main()

    sys.exit(0)

