#!/usr/bin/env bash

usage(){

cat <<EOS

Usage:

  CMD: ${0##*/} test.json

EOS

exit 0

}

INPUT_FILE_NAME=$1;shift;

if [ -z $INPUT_FILE_NAME ];then

  usage

fi

echo  $INPUT_FILE_NAME | java -jar /home/aine/script-sketch/java/00078-java-jsonデータをtable形式に変換/build/libs/json2table-1.0-SNAPSHOT-all.jar
