#!/usr/bin/env bash

INCLUDE_LIST="executable|Ruby script|shared object"
EXCLUDE_LIST="\.git|[A-Z][0-9]{2}"

SCRIPT_CMD_DIR_NAME=script-cmd
INSTALL_DIR_NAME=$HOME/.local/$SCRIPT_CMD_DIR_NAME/bin

mkdir -p $INSTALL_DIR_NAME

if [ ! -d $HOME/$SCRIPT_CMD_DIR_NAME ];then

  git clone https://github.com/ukijumotahaneniarukenia/$SCRIPT_CMD_DIR_NAME.git $HOME/$SCRIPT_CMD_DIR_NAME

fi

find $HOME/$SCRIPT_CMD_DIR_NAME -type f | grep -vP "$EXCLUDE_LIST" | xargs file | grep -P "$INCLUDE_LIST" | cut -d':' -f1 | sort -r | \
  while read f;do
    {
      CMD_HOST_VERSION=$(echo $f|grep -Po '[0-9]+?(-[0-9]+)+');
      echo ln -fsr $f $HOME/.local/$SCRIPT_CMD_DIR_NAME/bin/${f##*/};
      echo ln -fsr $f $HOME/.local/$SCRIPT_CMD_DIR_NAME/bin/${f##*/}-$CMD_HOST_VERSION;
    } | bash
  done

find $HOME/.local/$SCRIPT_CMD_DIR_NAME/bin -xtype l |xargs -I@ unlink @
