#!/usr/bin/env bash

#https://git-scm.com/book/ja/v2/Git-%E3%81%AE%E3%82%AB%E3%82%B9%E3%82%BF%E3%83%9E%E3%82%A4%E3%82%BA-Git-%E3%81%AE%E8%A8%AD%E5%AE%9A

#直感的ではないが、なれるようにする

#diff側はmergeを正にして引数の取る位置を調節していると考える

[ $# -eq 7 ] && gitmerge-p4merge-bash "$2" "$5"
